// Actual release build, real menu/debug input and material resource telemetry.
const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
 const output = '/tmp/malta-terrain-review'; fs.mkdirSync(output, {recursive:true});
 const server = spawn('python3', ['-m','http.server','8768','--bind','127.0.0.1','--directory',path.resolve(__dirname,'../builds/web')], {stdio:'ignore'});
 let browser; let checks = 0; const errors = []; const responses = [];
 const check = (condition, message) => {assert.ok(condition, message); checks++; console.log('PASS: ' + message);};
 try {
  await delay(500);
  browser = await chromium.launch({executablePath:process.env.CHROME_BIN || '/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page = await browser.newPage({viewport:{width:960,height:600}});
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => {if(message.type() === 'error') errors.push(message.text());});
  page.on('response', response => {if(response.status() >= 400) responses.push(response.url() + ': ' + response.status());});
  const state = () => page.evaluate(() => window.firstSortieState);
  const wait = (predicate, argument = null) => page.waitForFunction(predicate, argument, {timeout:120000});
  const click = async key => {const [x,y] = (await state())[key]; await page.mouse.click(x,y);};
  await page.goto('http://127.0.0.1:8768/index.html?smoke=1');
  await page.getByRole('button',{name:'PLAY IN BROWSER'}).click();
  await wait(() => window.firstSortieState?.selecting);
  const graphics = await page.evaluate(() => {
   const gl = document.getElementById('canvas').getContext('webgl2');
   return {version:gl.getParameter(gl.VERSION), renderer:gl.getParameter(gl.RENDERER)};
  });
  check(graphics.version.includes('WebGL 2'), 'Release renders through WebGL 2 / Compatibility');
  await click('malta_button');
  await wait(() => window.firstSortieState.airfield_selecting);
  await click('luqa_button');
  await wait(() => window.firstSortieState.home_airfield === 'luqa');
  await click('depart_button');
  await wait(() => window.firstSortieState.on_foot && window.firstSortieState.fleet_count === 6 && !!window.firstSortieState.terrain);
  const normal = await state();
  check(!normal.terrain.heatmap && !normal.terrain.debug_label_visible, 'Browser always starts Malta in normal mode');
  check(normal.terrain.material === 'res://assets/malta/materials/landscape.tres', 'Export loads the explicit landscape material resource');
  check(normal.terrain.mesh_count === 36 && normal.terrain.matching_meshes === 36, 'All 36 island meshes use the same intended material');
  check(normal.terrain.textures.length === 3 && normal.terrain.textures.every(p => p.startsWith('res://assets/malta/landscape/')) && !normal.terrain.vertex_colors_as_albedo, 'Default material loads bundled textures and ignores debug colours');
  check(normal.enemy_count === 1 && normal.home_airfield === 'luqa' && normal.hp === 100, 'Luqa departure, fleet, player health and one enemy remain intact');
  await page.keyboard.press('Escape');
  await wait(() => window.firstSortieState.paused);
  const world = (await state()).world_id;
  await page.screenshot({path:path.join(output,'web-luqa-normal.png')});
  await page.keyboard.press('F4');
  await wait(() => window.firstSortieState.terrain.heatmap);
  const debug = await state();
  check(debug.paused && debug.world_id === world, 'F4 changes render mode while keeping the same paused world');
  check(debug.terrain.material === 'res://assets/malta/materials/elevation_heatmap.tres' && debug.terrain.vertex_colors_as_albedo && debug.terrain.debug_label_visible, 'Deliberate debug loads the heatmap resource and displays its notice');
  check(debug.terrain.matching_meshes === 36, 'Debug applies consistently across all islands');
  await page.screenshot({path:path.join(output,'web-luqa-heatmap.png')});
  await page.keyboard.press('F4');
  await wait(() => !window.firstSortieState.terrain.heatmap);
  check((await state()).terrain.matching_meshes === 36 && !(await state()).terrain.debug_label_visible, 'F4 reliably restores landscape and hides the debug notice');
  await page.keyboard.press('Escape');
  await wait(() => !window.firstSortieState.paused);
  await page.keyboard.press('e');
  await wait(() => !window.firstSortieState.on_foot);
  check(!(await state()).engine_running && (await state()).world_id === world, 'Boarding remains in the same world with the engine off');
  await page.keyboard.press('i');
  await wait(() => window.firstSortieState.engine_running);
  await page.keyboard.down('w'); await page.keyboard.down('f');
  await wait(() => window.firstSortieState.throttle > 0.1 && window.firstSortieState.shots > 8);
  await page.keyboard.up('w'); await page.keyboard.up('f');
  check((await state()).engine_running && (await state()).hp === 100, 'Engine startup, throttle and weapon input remain functional');
  await page.keyboard.press('r');
  await wait(previousWorld => window.firstSortieState.on_foot && window.firstSortieState.world_id !== previousWorld && window.firstSortieState.fleet_count === 6, world);
  check(!(await state()).terrain.heatmap && (await state()).terrain.matching_meshes === 36, 'Full restart still defaults to landscape on a fresh world');
  check(errors.length === 0 && responses.length === 0, 'No shader, resource, JavaScript or HTTP errors in the release build');
  fs.writeFileSync(path.join(output,'web-results.json'), JSON.stringify({checks, errors, responses, graphics, normal, debug, final:await state()}, null, 2));
  console.log(`MALTA TERRAIN WEB RESULT: ${checks}/${checks} passed`);
 } finally {if(browser) await browser.close(); server.kill();}
})().catch(error => {console.error(error); process.exitCode = 1;});
