// Focused release-browser checks after the native Malta integrations.
const {chromium} = require('playwright');
const {spawn} = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const delay = ms => new Promise(resolve => setTimeout(resolve,ms));
(async()=>{
 const server=spawn('python3',['-m','http.server','8766','--bind','127.0.0.1','--directory',path.resolve(__dirname,'../builds/web')],{stdio:'ignore'});
 let browser;let checks=0;const errors=[];
 const check=(condition,label)=>{assert.ok(condition,label);checks++;console.log('PASS: '+label);};
 try{
  await delay(500);
  browser=await chromium.launch({executablePath:process.env.CHROME_BIN||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:960,height:600}});
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  const state=()=>page.evaluate(()=>window.firstSortieState);
  const wait=p=>page.waitForFunction(p,null,{timeout:120000});
  const click=async id=>{const [x,y]=(await state())[id];await page.mouse.click(x,y);};
  await page.goto('http://127.0.0.1:8766/index.html?smoke=1');
  await page.getByRole('button',{name:'PLAY IN BROWSER'}).click();
  await wait(()=>window.firstSortieState?.selecting);
  await click('malta_button');
  await wait(()=>window.firstSortieState.airfield_selecting);
  check((await state()).home_airfield==='ta_qali','Current release loads chart and Ta Qali selection');
  await click('depart_button');
  await wait(()=>window.firstSortieState.on_foot && window.firstSortieState.fleet_count===6);
  check((await state()).enemy_count===1,'Single Malta world starts six parked planes and one enemy');
  await page.keyboard.press('Escape');
  await wait(()=>window.firstSortieState.paused);
  check((await state()).on_foot,'Escape pauses while walking');
  await page.keyboard.press('Escape');
  await wait(()=>!window.firstSortieState.paused);
  check((await state()).on_foot,'Escape resumes while walking');
  await page.keyboard.press('e');
  await wait(()=>!window.firstSortieState.on_foot);
  const world=(await state()).world_id;
  check(!(await state()).engine_running,'Boarding keeps engine off');
  await page.keyboard.press('m');
  await wait(()=>window.firstSortieState.map_open);
  check(!(await state()).paused,'Visible navigation runs without pausing');
  await page.screenshot({path:'/tmp/first-sortie-web-checks/malta-current.png'});
  await page.keyboard.press('m');
  await page.keyboard.press('i');
  await wait(()=>window.firstSortieState.engine_running);
  check((await state()).engine_running,'Engine start remains working');
  await page.keyboard.press('i');
  await wait(()=>!window.firstSortieState.engine_running);
  await page.keyboard.press('h');
  await wait(()=>window.firstSortieState.hp===90);
  await page.keyboard.press('e');
  await wait(()=>window.firstSortieState.on_foot);
  check((await state()).hp===90 && (await state()).world_id===world,'Damage persists on exit in the same environment');
  await page.keyboard.press('r');
  await wait(()=>window.firstSortieState.hp===100 && window.firstSortieState.on_foot);
  check((await state()).world_id!==world && (await state()).enemy_count===1 && (await state()).fleet_count===6,'Full restart replaces the world with clean state exactly once');
  check(errors.length===0,'No current-release browser runtime errors');
  fs.writeFileSync('/tmp/first-sortie-web-checks/malta-current-results.json',JSON.stringify({checks,errors,state:await state()},null,2));
  console.log(`MALTA WEB RESULT: ${checks}/${checks} passed`);
 }finally{if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
